/** Option lists shared by the admin and vendor-portal equipment forms. */

export const EQUIPMENT_CATEGORIES = [
  { value: "xray_digital", label: "Digital X-Ray" },
  { value: "xray_mobile", label: "Mobile X-Ray" },
  { value: "xray_portable", label: "Portable X-Ray" },
  { value: "fluoroscopy", label: "Fluoroscopy" },
  { value: "c_arm", label: "C-Arm" },
  { value: "ultrasound_general", label: "General Ultrasound" },
  { value: "ultrasound_3d_4d", label: "3D/4D Ultrasound" },
  { value: "ultrasound_portable", label: "Portable Ultrasound" },
  { value: "doppler", label: "Doppler" },
  { value: "mammography_digital", label: "Digital Mammography" },
  { value: "mammography_3d", label: "3D Mammography" },
  { value: "ct_scanner", label: "CT Scanner" },
  { value: "ct_scanner_multi_slice", label: "Multi-Slice CT Scanner" },
  { value: "mri_scanner", label: "MRI Scanner" },
  { value: "mri_open", label: "Open MRI" },
  { value: "linear_accelerator", label: "Linear Accelerator" },
  { value: "brachytherapy", label: "Brachytherapy" },
  { value: "cobalt_60", label: "Cobalt-60" },
  { value: "treatment_planning", label: "Treatment Planning" },
  { value: "simulator", label: "Simulator" },
  { value: "gamma_camera", label: "Gamma Camera" },
  { value: "spect", label: "SPECT" },
  { value: "pet_scanner", label: "PET Scanner" },
  { value: "pet_ct", label: "PET-CT" },
  { value: "cyclotron", label: "Cyclotron" },
  { value: "angiography", label: "Angiography" },
  { value: "cath_lab", label: "Cath Lab" },
  { value: "dsa", label: "DSA" },
  { value: "ecg", label: "ECG" },
  { value: "echocardiography", label: "Echocardiography" },
  { value: "holter_monitor", label: "Holter Monitor" },
  { value: "stress_test", label: "Stress Test" },
  { value: "pacemaker_programmer", label: "Pacemaker Programmer" },
  { value: "tmt", label: "TMT" },
  { value: "anesthesia_machine", label: "Anesthesia Machine" },
];

export const EQUIPMENT_STATUS_OPTIONS = [
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
  { value: "maintenance", label: "Maintenance" },
  { value: "decommissioned", label: "Decommissioned" },
  { value: "pending_installation", label: "Pending Installation" },
];
